clc;
clear all;
close all;

addpath(genpath(pwd));

%% Gradient descent
x0 = [-1.0; -1.0];
niter = 1e2;
convergence = 1e-5;

##x = gradient_descent( ...
##    @himmelblau, ...
##    @grad_himmelblau, ...
##    x0, ...
##    niter, ...
##    convergence, ...
##    1e-4 ...
##);

##x = nesterov_accelerated_gradient_descent( ...
##    @himmelblau, ...
##    @grad_himmelblau, ...
##    x0, ...
##    niter, ...
##    convergence ...
##);

x = bfgs( ...
    @himmelblau, ...
    @grad_himmelblau, ...
    x0, ...
    niter, ...
    convergence ...
);

##x = conjugate_gradient_descent( ...
##    @himmelblau, ...
##    @grad_himmelblau, ...
##    x0, ...
##    niter, ...
##    convergence ...
##);
##
##x = newton( ...
##    @himmelblau, ...
##    @grad_himmelblau, ...
##    @invhes_himmelblau, ...
##    x0, ...
##    niter, ...
##    convergence ...
##);

